# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee1a11d0a28976615abf6d412c966d4f"
name = "boxMeter"
application_url = "https://boxmeter-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "https://boxmeter-production.up.railway.app/customers/data_request"
  compliance_topics = [ "customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "https://boxmeter-production.up.railway.app/customers/redact"
  compliance_topics = [ "customers/redact"]

  [[webhooks.subscriptions]]
  uri = "https://boxmeter-production.up.railway.app/shop/redact"
  compliance_topics = [ "shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://boxmeter-production.up.railway.app/auth/callback" ]
